version: '3'
services:
  apache-php-java:
    build:
      context: .
      dockerfile: Dockerfile
    image: textpdf_converter:latest
    container_name: textpdf_converter
    ports:
      - 8089:80
    volumes:
      - ./src:/var/www/html

